TaskCalendar/Models/Task.cs
using System;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace TaskCalendar.Models
{
    public class Task
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

TaskCalendar/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TaskCalendar.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }
    }
}

TaskCalendar/Controllers/CreateTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using TaskCalendar.Domain.Core;
using TaskCalendar.Infrastructure.Data.Repository;
using TaskCalendar.Infrastructure.Data.Context;

namespace TaskCalendar.Controllers
{
    public class CreateTaskController : Controller
    {
        /*TaskContext db = new TaskContext();*/

        private TaskRepository _taskRepository = new TaskRepository(new DataBaseContext());
        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Task entity)
        {
            bool result = _taskRepository.CreateTask(entity);

            if (result)
            {
                return Redirect("/Home");
            }

            return new HttpStatusCodeResult(400);
        }
    }
}

TaskCalendar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;

using TaskCalendar.Domain.Core;
using TaskCalendar.Infrastructure.Data.Context;
using TaskCalendar.Infrastructure.Data.Repository;

namespace TaskCalendar.Controllers
{
    public class HomeController : Controller
    {
        private DataBaseContext _dbContext = new DataBaseContext();
        private TaskRepository _taskRepository;

        public HomeController()
        {
            _taskRepository = new TaskRepository(_dbContext);
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.TaskIndexList = new List<int>() { 0, 1, 2, 3, 4 };

            return View(_taskRepository.GetTaskList());
        }

        public ActionResult DeleteModal(int id)
        {
            Task task = _taskRepository.Find(id);

            if (task == null)
            {
                return new HttpStatusCodeResult(400);
            }

            return PartialView("_DeleteModal", task);
        }

        [HttpPost]
        public ActionResult TaskSearch(string title)
        {
            var tasks = _taskRepository.SearchTask(title);
            return View("~/Views/Home/Index.cshtml", tasks);
        }

        [HttpPost]
        public ActionResult DeleteTask(int id)
        {
            Task task = _taskRepository.Find(id);

            if (task == null)
            {
                return new HttpStatusCodeResult(400);
            }

            bool status = _taskRepository.Remove(task);

            /*if (status)
            {
                ViewBag.DeleteStatus = "Запись успешно удалена";
            }
            else
            {
                ViewBag.DeleteStatus = "Не удалось удалить запись";
            }*/

            return Redirect("/");
        }
    }
}

TaskCalendar/Views/Calendar/Index.cshtml
@{
    ViewBag.Title = "Календарь";

    var nowDay = DateTime.Today;
    int daysInMounth = DateTime.DaysInMonth(nowDay.Day, nowDay.Month);
    int weeksInMounth = daysInMounth / 7;

    int startDayWeekIndex = (int)new DateTime(nowDay.Year, nowDay.Month, 1).DayOfWeek;


    Dictionary<int, List<string>> calendar = new Dictionary<int, List<string>> { };
    int currentDay = 1;

    for (int i = 1; i <= 5; i++)
    {
        calendar.Add(i, new List<string>());

        for (int d = currentDay; d < currentDay + 7; d++)
        {
            if (currentDay == 1 && d < startDayWeekIndex)
            {
                calendar[i].Add("");
            }
            else if (daysInMounth < (d - startDayWeekIndex + 1))
            {
                calendar[i].Add((d - daysInMounth - startDayWeekIndex + 1).ToString());
            }
            else
            {
                calendar[i].Add((d - startDayWeekIndex + 1).ToString());
            }
        }

        currentDay = currentDay + 7 <= daysInMounth ? currentDay + 7 : currentDay + 10;

        if (currentDay > daysInMounth)
        {
            break;
        }
    }
}

@section Body {
    <div class="row d-flex justify-content-between mt-4 mb-3">
        <p class="font-weight-bold" style="font-size: 1.5rem">18 апреля 2021</p>
        <div>
            <button class="btn btn-secondary">Пред.</button>
            <button class="btn btn-primary">След.</button>
        </div>
    </div>

    <div class="row">
        <table class="table table-bordered calendar-table">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Понедельник</th>
                    <th scope="col">Вторник</th>
                    <th scope="col">Среда</th>
                    <th scope="col">Четверг</th>
                    <th scope="col">Пятница</th>
                    <th scope="col">Суббота</th>
                    <th scope="col">Воскресенье</th>
                </tr>
            </thead>
            <tbody>

                @for (int w = 1; w < calendar.Count + 1; w++)
                {
                    <tr>
                        @for (int d = 0; d < calendar[w].Count; d++)
                        {
                            <th>@calendar[w][d]</th>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <script>

    </script>
}

TaskCalendar/Views/CreateTask/Index.cshtml
@model TaskCalendar.Domain.Core.Task

@{
    ViewBag.Title = "Создание задачи";

    List<SelectListItem> taskStatusIndexList = new List<SelectListItem>() {
        new SelectListItem {Value = "0", Text = "Новая", Selected = true},
        new SelectListItem {Value = "1", Text = "Активная"},
        new SelectListItem {Value = "2", Text = "Готова"},
        new SelectListItem {Value = "3", Text = "Готовая к deploy"}
    };
}

@section Body {
    <div class="mt-4">
        @using (Html.BeginForm("Index", "CreateTask", FormMethod.Post, new { @class = "create-task" }))
        {
            <div class="form-group">
                <label for="exampleInputEmail1">Название идеи</label>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @id = "exampleInputEmail1", @placeholder = "Назание" } })
                <small id="emailHelp" class="form-text">*Поле обязательное для заполнения</small>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Описание</label>
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "exampleFormControlTextarea1", @rows = "3" })
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Статус задачи</label>
                @Html.DropDownListFor(model => model.Status, taskStatusIndexList, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-primary" onclick="validateForm">Создать</button>
            <button type="button" class="btn btn-secondary">Очистить</button>
        }
    </div>

    <script>
        function validateForm(event) {
            const titleValue = $('#exampleInputEmail1').val()

            if (!titleValue || !titleValue.length) {
                event.preventDefault();

                $('#exampleInputEmail1').addClass("is-invalid");
                $("#emailHelp").css("color", "red");
                return;
            }
        }

        $(".create-task").submit(validateForm);

        $("button[type='button']").click(() => {
            $(".create-task").trigger("reset");

            $("#emailHelp").css("color", "inherit");
            $('#exampleInputEmail1').removeClass("is-invalid");
        })
    </script>
}

TaskCalendar/Views/Home/Index.cshtml
@model IEnumerable<TaskCalendar.Domain.Core.Task>

@{
    ViewBag.Title = "Task Calendare";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@functions
{
    public string taskStatus(int statusValue)
    {
        string status;

        switch (statusValue)
        {
            case 0:
                status = "Новый";
                break;
            case 1:
                status = "Активынй";
                break;
            case 2:
                status = "Готова";
                break;
            case 3:
                status = "Готова к Deploy";
                break;
            default:
                status = "Новый";
                break;
        }

        return status;
    }
}

@section Body {
    @*test add from branch master*@
    <div class="modal fade" role="dialog"></div>
    <div class="row mt-4" style="row-gap: 20px;">
        @if (Model.Count() == 0)
        {
            <p class="w-100 text-center text-uppercase font-weight-bold"
               style="height: calc(90vh - 100px); display: flex; align-items: center; justify-content: center; font-size: 1.8rem;">
                &#128556; Задачи отсутствуют &#128532;
            </p>
        }
        else
        {
            foreach (TaskCalendar.Domain.Core.Task task in Model)
            {
                <div class="card w-100">
                    <div class="card-header d-flex justify-content-between">
                        <p class="text-uppercase font-weight-bold m-0">@task.Title</p>
                        <p class="m-0">Дата создания: @task.CreatedAt</p>
                        @Html.ActionLink("Удалить", "DeleteModal", new { id = @task.Id }, new { @class = "viewDialog" })
                        @*@Ajax.ActionLink("Удалить", "DeleteTask", new { id = @task.Id }, new AjaxOptions { HttpMethod = "POST" }, new { @class = "close" })*@
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>@task.Description</p>
                            <footer class="blockquote-footer">Статус задачи: @taskStatus(@task.Status)</footer>
                        </blockquote>
                    </div>
                    @*<div class="form-group pl-4 pr-4">
                            <label for="exampleFormControlSelect1">Изменить статус</label>
                            <select class="form-control" id="exampleFormControlSelect1">
                                @foreach (var index in ViewBag.TaskIndexList)
                                {
                                    <option>@taskStatus(index)</option>
                                }
                            </select>
                        </div>*@
                </div>
            }
        }
    </div>

    <script>
        $.ajaxSetup({ cache: false });

        $(".viewDialog").click(function (e) {

            e.preventDefault();
            $("body").addClass("modal-open");
            $.get(this.href, function (data) {
                $('.modal').html(data);
                $('.modal').modal('show');
            });
        });
    </script>
}

TaskCalendar/Views/Home/_DeleteModal.cshtml
@model TaskCalendar.Domain.Core.Task

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Удаление записи</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Вы действительно хотите удалить запись <b>"@Html.DisplayFor(model => model.Title)"</b>?</p>
        </div>
        <div class="modal-footer">
            @using (Html.BeginForm("DeleteTask", "Home"))
            {
                @Html.Hidden("id", Model.Id)

                <button type="submit" class="btn btn-danger">Удалить</button>
            }
            @*@Ajax.ActionLink("Удалить", "DeleteTask", new { id = Model.Id }, new AjaxOptions { HttpMethod = "POST" }, new { @class = "btn btn-danger" })*@
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
        </div>
    </div>
</div>

TaskCalendar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="@Url.Content("~/Content/themes/base/all.css")" rel="stylesheet" />

    <script src="@Url.Content("~/Scripts/jquery-3.6.0.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.13.1.min.js")"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark">
            @Html.RouteLink("Task_Сalendare", new { controller = "Home", action = "Index" }, new { @class = "navbar-brand text-white" })
            <div class="navbar-nav flex-row" style="column-gap: 20px;">
                @Html.RouteLink("Главная", new { controller = "Home", action = "Index" }, new { @class = "nav-item nav-link" })
                @Html.RouteLink("Создать", new { controller = "CreateTask", action = "Index" }, new { @class = "nav-item nav-link" })
                @Html.RouteLink("Календарь", new { controller = "Calendar", action = "Index" }, new { @class = "nav-item nav-link" })
            </div>
            @using (Ajax.BeginForm("TaskSearch", "Home", new AjaxOptions { UpdateTargetId = "result" }, new { @class = "form-inline" }))
            {
                <input class="form-control mr-sm-2" name="title" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
            }
        </nav>
    </header>

    <div class="container body-content">
        @RenderSection("Body")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>